package ua.example.springcourse.SpringSecurity.models;

import javax.annotation.processing.Generated;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.validation.groups.Default;


/*
   CREATE TABLE Person(
   id int PRIMAL KEY GENERATED BY DEFAULT AS IDENTITY,
   username varchar NOT NULL,
   year_of_birthday int NOT NULL,
   password varchar NOT NULL
   )
    */
@Entity
@Table(name = "Person")
public class Person {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int id;

    @Column(name = "username")
    @NotNull(message = "mush be not empty")
    @Size(min = 3, max = 100, message = "must be not more than 100 letter")
    private String username;

    @Column(name = "year_of_birthday" )
    @NotNull(message = "mush be not empty")
    private int year_of_birthday;

    @Column (name = "password")
    @NotNull(message = "mush be not empty")
    private String password;

    @Column(name = "role")
    @NotNull
    private String role;


    public Person(){
    }

    public Person(String username, int year_of_birthday, String password) {
        this.username = username;
        this.year_of_birthday = year_of_birthday;
        this.password = password;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public int getYear_of_birthday() {
        return year_of_birthday;
    }

    public void setYear_of_birthday(int year_of_birthday) {
        this.year_of_birthday = year_of_birthday;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    @Override
    public String toString() {
        return "Person{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", year_of_birthday=" + year_of_birthday +
                ", password=" + password +
                '}';
    }
}
