package ua.example.SpringRest.models;

import org.hibernate.annotations.Cascade;

import javax.persistence.*;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import java.time.LocalDateTime;

/*
CREATE TABLE Measurements(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    value int CHECK ( value < 100 and value > -100 ) NOT NULL,
    raining boolean NOT NULL,
    sensor VARCHAR REFERENCES Sensor (name) on delete CASCADE NOT NULL,
    timeToDo TIMESTAMP
);
 */
@Entity
@Table(name = "Measurements")
public class Measurements {

    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;


    @NotNull
    @Column(name = "value")
    @Min(value = -100, message = "mush be more than -100")
    @Max(value = 100, message = "mush be least than -100")
    private Integer value;

    @NotNull
    @Column(name = "raining")
    private Boolean raining;

    @NotNull
    @ManyToOne
    @JoinColumn(name = "sensor", referencedColumnName = "name")
    private Sensor sensor;

    @Column(name = "timeToDo")
    private LocalDateTime timeToDo;

    public Measurements(int value, boolean raining, Sensor sensor) {
        this.value = value;
        this.raining = raining;
        this.sensor = sensor;
    }

    public Measurements() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getValue() {
        return value;
    }

    public void setValue(int value) {
        this.value = value;
    }

    public boolean isRaining() {
        return raining;
    }

    public void setRaining(boolean raining) {
        this.raining = raining;
    }

    public Sensor getSensor() {
        return sensor;
    }

    public void setSensor(Sensor sensor) {
        this.sensor = sensor;
    }

    public LocalDateTime getTimeToDo() {
        return timeToDo;
    }

    public void setTimeToDo(LocalDateTime timeToDo) {
        this.timeToDo = timeToDo;
    }

    @Override
    public String toString() {
        return "Measurements{" +
                "value=" + value +
                ", raining=" + raining +
                ", sensor=" + sensor +
                ", timeToDo=" + timeToDo +
                '}';
    }
}
