package ua.example.SpringRest.models;


import javax.persistence.*;
import javax.validation.constraints.NotNull;

/*
CREATE TABLE Sensor(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR UNIQUE NOT NULL
);
 */
@Entity
@Table(name = "sensor")
public class Sensor {

    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @NotNull
    @Column(name = "name")
    private String name;

    public Sensor(String name) {
        this.name = name;
    }

    public Sensor() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
